-- MySQL Script generated by MySQL Workbench
-- Fri Sep  3 10:43:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Alias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Alias` (
  `idAlias` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apodo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlias`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Apuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Apuesta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Apuesta` (
  `idApuesta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valorApuesta` INT NOT NULL,
  `id_Pelea` INT UNSIGNED NOT NULL,
  `id_Apostador1` INT UNSIGNED NOT NULL,
  `id_Apostador2` INT UNSIGNED NOT NULL,
  `id_L_Apostador1` INT UNSIGNED NOT NULL,
  `id_L_Apostador2` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idApuesta`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Celda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Celda` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Celda` (
  `idCelda` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dimensiones` VARCHAR(45) NOT NULL,
  `generoCelda` ENUM("F", "M") NOT NULL,
  `capacidadMax` INT NOT NULL,
  PRIMARY KEY (`idCelda`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Comodidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comodidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Comodidad` (
  `idComodidad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComodidad`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ComodidadxCelda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ComodidadxCelda` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ComodidadxCelda` (
  `id_Celda` INT UNSIGNED NOT NULL,
  `id_Comodidad` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Celda`, `id_Comodidad`))
ENGINE = InnoDB;

SHOW WARNINGS;
-- -----------------------------------------------------
-- Table `Condena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Condena` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Condena` (
  `idCondena` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fechaSentencia` DATE NOT NULL,
  `tiempoCondena` TINYINT NOT NULL,
  `inicioCondena` DATE NOT NULL,
  `finCondena` DATE NOT NULL,
  `id_Celda` INT UNSIGNED NOT NULL,
  `id_Persona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCondena`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Delito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Delito` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Delito` (
  `idDelito` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDelito`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `DelitoxCondena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DelitoxCondena` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `DelitoxCondena` (
  `id_Condena` INT UNSIGNED NOT NULL,
  `id_Delito` INT NOT NULL,
  PRIMARY KEY (`id_Condena`, `id_Delito`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Escenario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Escenario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Escenario` (
  `idEscenario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `decripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEscenario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GuardianxCelda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GuardianxCelda` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `GuardianxCelda` (
  `id_Persona` INT UNSIGNED NOT NULL,
  `id_Celda` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Persona`, `id_Celda`))
ENGINE = InnoDB;

SHOW WARNINGS;
-- -----------------------------------------------------
-- Table `JuezxCondena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JuezxCondena` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `JuezxCondena` (
  `id_Condena` INT UNSIGNED NOT NULL,
  `id_Persona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Condena`, `id_Persona`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pelea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pelea` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pelea` (
  `idPelea` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoria` ENUM("F", "M") NOT NULL,
  `armaPeleador1` VARCHAR(45) NOT NULL,
  `armaPeleador2` VARCHAR(45) NOT NULL,
  `ganador` INT NULL,
  `id_Peleador1` INT UNSIGNED NOT NULL,
  `id_Peleador2` INT UNSIGNED NOT NULL,
  `id_Escenario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPelea`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Persona` (
  `idPersona` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `fechaNacimiento` VARCHAR(45) NOT NULL,
  `salarioGuardian` VARCHAR(45) NULL,
  `fechaIngresoGuardian` VARCHAR(45) NULL,
  `tipoPersona` ENUM("preso", "guardian", "juez") NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prisioneroxalias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prisioneroxalias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `prisioneroxalias` (
  `id_Alias` INT UNSIGNED NOT NULL,
  `id_Persona` INT UNSIGNED NOT NULL,
PRIMARY KEY (`id_Alias`, `id_Persona`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Construccion Llaves Foraneas
-- -----------------------------------------------------

ALTER TABLE Apuesta
ADD CONSTRAINT id_Pelea FOREIGN KEY (id_Pelea) REFERENCES Pelea(idPelea),
ADD CONSTRAINT id_Apostador1 FOREIGN KEY (id_Apostador1) REFERENCES Persona(idPersona),
ADD CONSTRAINT id_Apostador2 FOREIGN KEY (id_Apostador2) REFERENCES Persona(idPersona),
ADD CONSTRAINT id_L_Apostador1 FOREIGN KEY (id_L_Apostador1) REFERENCES Persona(idPersona),
ADD CONSTRAINT id_L_Apostador2 FOREIGN KEY (id_L_Apostador2) REFERENCES Persona(idPersona);

ALTER TABLE ComodidadxCelda
ADD CONSTRAINT id_Celda FOREIGN KEY (id_Celda) REFERENCES Celda(idCelda),
ADD CONSTRAINT id_Comodidad foreign key (id_Comodidad) REFERENCES Comodidad(idComodidad);

ALTER TABLE Condena
ADD CONSTRAINT id_CeldaxCondena FOREIGN KEY (id_Celda) REFERENCES Celda(idCelda),
ADD CONSTRAINT id_PersonaxCondena foreign key (id_Persona) REFERENCES Persona(idPersona);

ALTER TABLE DelitoxCondena
ADD CONSTRAINT id_CondenaxDelitoxCondena FOREIGN KEY (id_Condena) REFERENCES Condena(idCondena),
ADD constraint id_DelitoxDelitoxCondena foreign key (id_Delito) REFERENCES Delito(idDelito);

ALTER TABLE GuardianxCelda
add constraint id_PersonaxGuardianxCelda foreign key (id_Persona) REFERENCES Persona(idPersona),
add constraint id_CeldaxGuardianxCelda foreign key (id_Celda) REFERENCES Celda(idCelda);

ALTER table JuezxCondena
ADD CONSTRAINT id_CondenaxJuezxCondena foreign key (id_Condena) REFERENCES Condena(idCondena),
ADD CONSTRAINT id_PersonaxJuezxCondena foreign key (id_Persona) REFERENCES Persona(idPersona);

ALTER TABLE Pelea
ADD CONSTRAINT id_Peleador1xPelea foreign key (id_Peleador1) REFERENCES Persona(idPersona),
ADD CONSTRAINT id_Peleador2xPelea foreign key (id_Peleador2) REFERENCES Persona(idPersona),
ADD CONSTRAINT id_EscenarioxPelea foreign key (id_Escenario) REFERENCES Escenario(idEscenario);

ALTER TABLE prisioneroxalias
ADD CONSTRAINT id_Aliasxprisioneroxalias foreign key (id_Alias) REFERENCES Alias(idAlias),
ADD CONSTRAINT id_Personaxprisioneroxalias foreign key (id_Persona) REFERENCES Persona(idPersona);

-- ------------------------------------------------
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
